### ISSUE TITLE
get_room_name() returns empty if roomname starts with #

### ISSUE THREAD

**Issue by betz** [matrix-org/matrix-python-sdk#214] opened 2018-05-22 01:25 UTC
Found out that the method get_room_name() returns nothing when a room name starts with a #.
Was hard to find the bug. Just had this one room bugging :). 

2 rooms i have no return:
- #matrix-dev:matrix.org
- #darknet:matrix.org

**Comment by non-Jedi** [comment] 2018-05-22 02:36
Hi @betz. Are you talking about `MatrixHttpApi.get_room_name`? I just tested with `#matrix-dev:matrix.org`, and it worked as expected. In fact, looking at code, I can't imagine it **not** working as expected. See session below:

```python
In [1]: from matrix_client.client import MatrixClient

In [3]: c = MatrixClient("https://matrix.org")

In [4]: c.register_as_guest()
Out[4]: '<redacted>'

In [5]: c.join_room("#matrix-dev:matrix.org")
Out[5]: <matrix_client.room.Room at 0x7fc24205e860>

In [6]: c.rooms
Out[6]: {'!XqBunHwQIXUiqCaoxq:matrix.org': <matrix_client.room.Room at 0x7fc24205e860>}

In [8]: c.api.get_room_name("!XqBunHwQIXUiqCaoxq:matrix.org")
Out[8]: {'name': '#matrix-dev:matrix.org'}
```

**Comment by non-Jedi** [comment] 2018-08-06 14:30
Closing this as unable to reproduce. Please comment here, and I'll reopen if you can provide more info @betz

**Closed by non-Jedi** 2018-08-06 14:30 UTC
Labels: Awaiting Changes, bug
